---
title: "Modelfitting"
author: "Simon&Andrea"
date: '2022-10-120'
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(tidyverse, rjson, DEoptim, doParallel, here,data.table,jsonlite,lme4,nnet,rstan,brms)
knitr::opts_knit$set(root.dir = here()) # set root fot the whole file
refit=T
```

In this document, we will fit learning model to the "social bandit" task that Andrea and I developed. 
First, lets load some data.

```{r}
social_data <-  read_csv(file = paste0("./data/social/data_social_all_participants.csv"))
social_data<-social_data%>%mutate(player=ifelse(group=="adults",player,player+1000))

## get unreasonable nans
nans<-social_data%>%
  filter(is.na(demo_type) | is.na(cells))%>%pull(player)%>%unique()

social_data<-social_data%>%filter(!(player %in% nans))
R_subj=social_data%>%group_by(player)%>%summarise(n_r=length(unique(round)))%>%pull(n_r)


social_data<-social_data%>%#drop_na()
  filter(!is.na(demo_type) & !is.na(cells))%>%#filter(player<30)%>%# get a sub-sample of both adults and adolescents 
  mutate(soctype=case_when(
    demo_type=="gem_found"~3,# i need that to index the different social weight parameters
    demo_type=="gem_not_found" | demo_type=="no_gem"~2,
    str_detect(demo_type,"never_exploit") ~ 1
  )
  )
#give kids a unqiquely numbered indx
R_subj=social_data%>%group_by(player)%>%summarise(n_r=length(unique(round)))%>%pull(n_r)
#keep<-unique(social_data$player)[R_subj==12]# keep only participants who completed all trials
keep_forfit_adults<-social_data%>%filter(group=="adults")%>%pull(player)%>%unique()#[R_subj==12]# keep only participants who completed all trials
keep_forfit_adolescents<-social_data%>%filter(group=="adolescents")%>%pull(player)%>%unique()#[R_subj==12]# keep only participants who completed all trials

```

```{r}
data_list_adults<-readRDS(file = "A_GeneratedFiles/data_list_adults.rds")
data_list_adolescents<-readRDS(file = "A_GeneratedFiles/data_list_adolescents.rds")

#range normalization
rewards_new_adol<-data_list_adolescents$rewards
# rescale rewards for adolescents
for (x in 1:length(data_list_adolescents$rewards[1,,1])){
  for (y in 1:length(data_list_adolescents$rewards[1,1,])){
    for (z in 1:length(data_list_adolescents$rewards[,1,1])){
      
      rewards_new_adol[z,x,y]=ifelse(data_list_adolescents$gem_found[z,x,y]==2,
                                     (data_list_adolescents$rewards[z,x,y]+75)/150,
                                     (data_list_adolescents$rewards[z,x,y]+75)/363
                                     
      )
    }
  }
}

# rescale rewards for adults
rewards_new_adul<-data_list_adults$rewards
for (x in 1:length(data_list_adults$rewards[1,,1])){
  for (y in 1:length(data_list_adults$rewards[1,1,])){
    for (z in 1:length(data_list_adults$rewards[,1,1])){
      rewards_new_adul[z,x,y]=ifelse(data_list_adults$gem_found[z,x,y]==2,
                                     (data_list_adults$rewards[z,x,y]+75)/150,
                                     (data_list_adults$rewards[z,x,y]+75)/363
      )
    }
  }
}

data_list_adolescents$rewards<-rewards_new_adol
data_list_adults$rewards<-rewards_new_adul

```

# Fit stanmodel

```{r}
options(buildtools.check = function(action) TRUE)

model_compiled<-stan_model(
  model_name = "Q_sw_rangenorm",
  file="./C_modelfittingCode/stan/model_code/Q_nokeeper_sw_gem_nogem_range_n.stan",
  allow_optimizations=T,
  warn_pedantic=T
)
```

```{r}
Q_mod_adol<-sampling(
  model_compiled,
  data=data_list_adolescents,
  pars =c("lr","tau","sw","log_lik"),
  init=0,
  iter = 2000,
  chains=4,
  cores=4
)

saveRDS(object = Q_mod_adol,file = "./A_GeneratedFiles/modelfits/Q_nokeeper_sw_gem_nogem_range_n_adolescents.rds")
#Q_mod_adol<-readRDS(file = "./A_GeneratedFiles/modelfits/Q_sw_gem_nogem_stan_adolescents.rds")

```

```{r}
Q_mod_adul<-sampling(
  model_compiled,
  data=data_list_adults,
  pars =c("lr","tau","sw","log_lik"),
  # init=1,
  iter = 4000,
  chains=6,
  cores=6
)

saveRDS(object = Q_mod_adul,file = "./A_GeneratedFiles/modelfits/Q_nokeeper_sw_gem_nogem_range_n_adults.rds")

```

# did that make any sense
```{r}
# # current benchmark
#Q_mod_adul_2<-readRDS(file = "./A_GeneratedFiles/modelfits/Q_sw_gem_nogem_stan_adults.rds")
#Q_mod_adol_2<-readRDS(file = "./A_GeneratedFiles/modelfits/Q_sw_gem_nogem_stan_adolescents.rds")

# 
# # compare models unsystematically. 
#Q_mod_adul_2_loglik<-loo::extract_log_lik(Q_mod_adol_2)
#Q_mod_adul_loglik<-loo::extract_log_lik(Q_mod_adol)
# # 
# # 
hist(Q_mod_adul_2_loglik-Q_mod_adul_loglik,breaks=100)
t.test(Q_mod_adul_2_loglik,Q_mod_adul_loglik)
```

```{r}
Q_mod_adol<-readRDS(file = "./A_GeneratedFiles/modelfits/Q_nokeeper_sw_gem_nogem_range_n_adolescents.rds")
Q_mod_adul<-readRDS(file = "./A_GeneratedFiles/modelfits/Q_nokeeper_sw_gem_nogem_range_n_adults.rds")

```

# join posterior draws and join them with original dataframe.

```{r}
# make data in long format
adults<-Q_mod_adul%>%
  tidybayes::gather_draws(lr[participant,gem],tau[participant,gem],sw[participant,gem])%>%
  mutate(
    group="adults",
    player = keep_forfit_adults[participant]
  )# get back original participant index

adolescents<-Q_mod_adol%>%
  tidybayes::gather_draws(lr[participant,gem],tau[participant,gem],sw[participant,gem])%>%
  mutate(
    group="adolescents",
    player = keep_forfit_adolescents[participant]
  )

all_draws<-rbind(adults,adolescents)
#all_draws<-adults
# pivot wider first for joining with rest of the data.
all_draws_summarized<-all_draws%>%group_by(player,group,.variable,gem)%>%
  dplyr::summarise(m_value=mean(.value))%>%pivot_wider(names_from = c(.variable,gem),values_from = m_value)

social_fits_d<-left_join(social_data,all_draws_summarized,by=c("player"))

#saveRDS(all_draws,file = "A_GeneratedFiles/modelfits/draws_Q_gem_nogem.rds")
#saveRDS(social_fits_d,file = "A_GeneratedFiles/modelfits/summed_Q_gem_nogem.rds")
```

#

```{r}
adolescents%>%#filter(.variable=="sw")%>%
  ggplot(aes(x=gem,y=.value,color=gem,group=gem))+
  stat_summary()+
  facet_wrap(.~ .variable)


adults%>%#filter(.variable=="sw")%>%
  ggplot(aes(x=gem,y=.value,color=gem,group=gem))+
  stat_summary()+
  facet_wrap(.~ .variable)

```

# plot parameter estimates

```{r}
pacman::p_load(tidyverse, gghalves, here, lmerTest, ggthemes, cowplot)


#all_draws<-readRDS("./A_GeneratedFiles/modelfits/draws_Q_gem_nogem.rds")
library("tidybayes")


# TODO: 
# add greek. 
all_draws%>%group_by(participant,group,.variable,gem)%>%
  dplyr::summarise(m_value=mean(.value))%>%
  ggplot(aes(x=group,y=m_value,group=interaction(gem,group),color=as.factor(gem)))+
  geom_point(position=position_dodge(0.9),alpha=0.05)+
  geom_half_boxplot(errorbar.draw = FALSE, notch = TRUE) +
  geom_half_point(alpha = .4) +
  scale_y_continuous(name="posterior parameter sample")+
  stat_summary(
    geom = "point",
    size = 1,
    stroke = 0.5,
    color = "black",
    fill = "orange",
    position = position_dodge(1)
  ) +
  #scale_color_discrete()+
  facet_wrap( ~ .variable,scales="free",labeller = labeller(gem=c(`1`="Gem Found",`2`="Gem Not Found")))+
  theme_bw(14)->plot

plot


```
