---
title: "Modelfitting"
author: "Simon&Andrea"
date: '2022-10-120'
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(tidyverse, rjson, DEoptim, doParallel, here)
knitr::opts_knit$set(root.dir = here()) # set root fot the whole file
```

In this document, we will fit a kalman filter to the "social bandit" task that Andrea and I developed. 
First, lets load some data.

```{r}
source("./C_modelfittingCode/models.R") # more reproducible

# load behavioral data
#explore_data <- read_csv(file = paste0("./Data/data_coord.csv"))
social_data<-read_csv(file = paste0("./data/social/data_social_coord.csv"))
```
# Fit model to social data
For this we need to know th

```{r}
source("./C_modelfittingCode/models_mle.R")
social_fits<-foreach(
  player_nr = unique(social_data$player),
  .packages = c("DEoptim", "dplyr"),
  .combine="rbind"
) %dopar% {
  # browser()
  Xnew <- as.matrix(expand.grid(0:7, 0:7)) # do this outside the loop for better speed
  output <- c()
  
  # social data TODO: concatenate nonsocial data.
  d1 <- subset(social_data, player == player_nr) %>%
    group_by(round) %>%
    mutate(z = (points - mean(points)) / sd(points)) %>%
    ungroup()
  
  # print(d1_round)
  
  rounds <- unique(d1$round)
  
  #for (r in rounds) { # loop through rounds in roundList
  cv <- fit_fun(
    d1 = d1, 
    learning_model_fun = bayesianMeanTracker, 
    acquisition_fun = ucb
  ) # only try one sub
  cv$p=player_nr
  #output <- rbind(output, cv)
  #}
  saveRDS(output, file = paste0("A_GeneratedFiles/modelfits/social_models/Q_fit_New_Bounds_by_round", playerNr, ".rds"))
}
```

