---
title: "Explore_data_for_social information"
author: "Andrea"
date: "2022-11-03"
output: html_document
---


```{r}

pacman::p_load(tidyverse, rjson, data.table, gghalves)

```


# Identify participants that can provide different types of social information

## relevant variables

- n of switches
- n of consecutive clicks
- n of gems founds

n of pointsearned vs. expected points (better than chance)

```{r load data, echo=FALSE, warning=FALSE, message=FALSE }

explore_data <- read_csv(file = "data/data_coord.csv")
 
explore_data <- explore_data %>% 
  filter(player != 188)
#nogems <- subset(explore_data, gempresent == 0)
                   
                   
simd_data <- NULL

for (n in 1:length(unique(explore_data$player))) {
  
  # all gems
  
  one_player <-  readRDS(file = paste0("A_GeneratedFiles/simulations/all_envs/simulated_choices", n))
  
  one_player <- one_player%>% 
    mutate(gem_label = ifelse(env_type == 1, "with gem", "no gem"))
  
  # only no gems
  # one_player <-  readRDS(file = paste0("A_GeneratedFiles/simulations/simulated_choices", n))
simd_data <- bind_rows(simd_data, one_player)
}

```

```{r merge datasets, warning=FALSE, echo=FALSE, message=FALSE}

  
simd_data <- simd_data %>% 
  select(playerNr, choice_index, points_new_choice, x_new_choice, y_new_choice, z_new_choice, env_type, env_counter, trial, learning_rate, temperature, env_number, ) %>% 
  rename(player = playerNr,
         x = x_new_choice,
         y = y_new_choice,
         z = z_new_choice,
         cells = choice_index,
         points = points_new_choice,
         gempresent = env_type,
         round = env_counter) %>% 
  mutate(gem = ifelse(points > 180, 1, 0),
         data_source = 'simulation')


par_data <- simd_data %>% 
  select(learning_rate, temperature)

explore_data <- explore_data %>% 
  mutate(mean_points = mean(points),
           sd_points = sd(points) ,
           z=(points-mean_points)/sd_points,
          data_source = 'experiment') %>% 
  select(player, points, cells, gempresent, gem, round, x, y, z, data_source, env_number) %>% 
  group_by(player, round) %>% 
  mutate(trial = 1:25)

explore_data <- bind_cols(explore_data, par_data) 

all_data <- bind_rows(simd_data, explore_data)

gems_coords <- all_data %>% 
  filter(data_source == "experiment" & points >160) %>% 
  select(x , y, env_number) %>% 
  distinct()


```

## heatmap of 


```{r}

all_data %>%
  filter(gempresent == 1) %>%
  ggplot(aes(x = x, y = y)) +
  geom_bin_2d(binwidth = c(1, 1)) +
  geom_rect(data=gems_coords, size=.5, fill=NA, colour="yellow",
  aes(xmin = x - 1, xmax = x  , ymin = y - 1, ymax = y )) +
  facet_wrap( ~ env_number + data_source, ncol = 4) 

```

```{r}

# explore exploit decisions

explore_exploit <- explore_data %>%
  group_by(player, round) %>%
  mutate(exploit = ifelse(lead(cells) == cells, 1, 0),
         explore = ifelse(lead(cells) != cells, 1, 0)) %>%
  mutate(out_cat = case_when(points > 150 ~ 1,
                             points < 0 ~ 3,
                             TRUE ~ 2)) %>% pivot_longer(cols = c(exploit, explore), names_to = "explore_exploit")


```
  
  