---
title: "Regressions analyses main text"
author: "Andrea & Simon"
output: html_document
---

## load packages and prepare data
```{r echo=FALSE, warning=FALSE, message=FALSE, echo=FALSE}

## load packages @andrea implement pck_mgmt script
pacman::p_load(tidyverse,
               rjson,
               data.table,
               gghalves,
               here,
               lme4,
               lmerTest,
               broom.mixed,
               infer,
               ggthemes,
               sjPlot)

'%!in%' <- function(x,y)!('%in%'(x,y))

options(scipen = 999,digits = 4)
```

```{r load data, echo=FALSE, warning=FALSE, message=FALSE }

## load data
all_data <- read_csv(file = paste0(here(), "/data/social/data_social_all_participants.csv")) %>% 
   mutate(demo_quality_f = as.factor(demo_quality),
         age_f = factor(group, levels = c("adults", "adolescents"))) ## mutate IVs into factors
```

## differences in points scored by group

```{r points by age group regression}

## vizualize mean player point performance
all_data %>% 
  ungroup() %>% 
  group_by(uniqueID) %>% 
  mutate(mean_points_player = mean(tot_points, na.rm = TRUE)) %>% 
  select(mean_points_player, age_f,uniqueID) %>% 
  distinct() %>% 
  ungroup() %>%
  ggplot(aes(x=age_f, y=mean_points_player))+
  geom_boxplot() +
  geom_point()


all_data %>% 
  ungroup() %>% 
  group_by(uniqueID) %>% 
  mutate(mean_points_player = mean(tot_points, na.rm = TRUE)) %>% 
  select(mean_points_player, age_f,uniqueID) %>% 
  distinct() %>% 
  ungroup() %>% 
  stats::t.test(mean_points_player ~ age_f, data = ., alternative = "two.sided", paired = FALSE)

all_data %>% 
  group_by(uniqueID) %>% 
  mutate(mean_points_player = mean(tot_points, na.rm = TRUE)) %>% 
  select(mean_points_player, age_f) %>% 
  distinct() %>% 
  ggplot()+
  geom_histogram(aes(x=mean_points_player))

## just raw difference in points across conditions## juTRUEst raw difference in points across conditions
t.test(tot_)

## select only one observation per participant
performance_age_demonstrator <- all_data %>%
  ungroup() %>%
  select(uniqueID, age_f, demo_quality_f, tot_points) %>%
  distinct() %>% 
 # group_by(uniqueID, demo_quality_f) %>% 
  mutate(mean_points = mean(tot_points, ),
         sd = sd(tot_points),
         scaled_points = (tot_points - mean_points)/(sd*0.5),
         treatment= factor(
            ifelse(demo_quality_f == "best" & age_f == "adults", "adu_best",
            ifelse(demo_quality_f == "medium" & age_f == "adults", "adu_medium",
            ifelse(demo_quality_f == "worst" & age_f == "adults", "adu_worst",
            ifelse(demo_quality_f == "best" & age_f == "adolescents", "ado_best",
            ifelse(demo_quality_f == "medium" & age_f == "adolescents", "ado_medium",
            ifelse(demo_quality_f == "worst" & age_f == "adolescents", "ado_worst", NA))))))))

## load model if fitting has been done, if not fit model
if #(file.exists(paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/performance_age_demonstrator_model.RData')) & 
(file.exists(paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/performance_age_demonstrator_model_scaled.RData')))
  #)  
  {
  
  # base::load(paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/performance_age_demonstrator_model.RData'))
  base::load(paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/performance_age_demonstrator_model_scaled.RData'))

  } else {

# ## model specification
# performance_age_demonstrator_model <-
#   brms::brm(formula = scaled_points ~ treatment+ (1 |  uniqueID),
#             data = performance_age_demonstrator,
#             iter = 6000)

# ## model specification
# performance_age_demonstrator_model <-
#   brms::brm(formula = tot_points ~ demo_quality_f * age_f + (1 |  uniqueID),
#             data = performance_age_demonstrator,
#             iter = 6000)
# 

## define priors 
prior_cauchy <- brms::prior_string("cauchy(0, 2.5)", class = "b")

## model specification
performance_age_demonstrator_model_scaled <-
  brms::brm(formula = scaled_points ~ demo_quality_f * age_f + (1 |  uniqueID),
            prior = prior_cauchy,
            sample_prior = TRUE,
            data = performance_age_demonstrator,
            iter = 6000)

## save
#save("performance_age_demonstrator_model", file = paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/performance_age_demonstrator_model.RData'))

## save
save("performance_age_demonstrator_model_scaled", file = paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/performance_age_demonstrator_model_scaled.RData'))

  }
#
# ## results
# tab_model(performance_age_demonstrator_model)
# plot_model(performance_age_demonstrator_model)
           
## results model 2
tab_model(performance_age_demonstrator_model_scaled)
plot_model(performance_age_demonstrator_model_scaled)


## bayes factor test main effects
# brms::hypothesis(performance_age_demonstrator_model,"age_fadolescents > 0", sample_prior = TRUE)
# brms::hypothesis(performance_age_demonstrator_model,"demo_quality_fmedium < 0")
# brms::hypothesis(performance_age_demonstrator_model,"demo_quality_fworst	 < 0") 
# 
# ## bayes factor test interactions
# brms::hypothesis(performance_age_demonstrator_model,"demo_quality_fmedium:age_fadolescents < 0")
# brms::hypothesis(performance_age_demonstrator_model,"demo_quality_fworst:age_fadolescents <  0")


# scaled model
## bayes factor test main effects
brms::hypothesis(performance_age_demonstrator_model_scaled,"age_fadolescents > 0")
brms::hypothesis(performance_age_demonstrator_model_scaled,"demo_quality_fmedium < 0")
brms::hypothesis(performance_age_demonstrator_model_scaled,"demo_quality_fworst	 < 0") 

## bayes factor test interactions
brms::hypothesis(performance_age_demonstrator_model_scaled,"demo_quality_fmedium:age_fadolescents < 0")
brms::hypothesis(performance_age_demonstrator_model_scaled,"demo_quality_fworst:age_fadolescents <  0")

```
## social larning differences

```{r}
## create count variable
model_random_slopes_data <- all_data %>%
  group_by(uniqueID, round, gem_found, age_f, demo_quality_f) %>%
  filter(social_info_use == "copy") %>%
  count(social_info_use)


## mean copy by group t_test
model_random_slopes_data %>% 
  ungroup() %>% 
  filter(n!=0) %>% 
  group_by(uniqueID) %>% 
  mutate(mean_copy = mean(n), na.rm = TRUE) %>% 
  select(age_f, uniqueID, mean_copy) %>% 
  distinct() %>% 
  t.test(mean_copy ~ age_f, data = ., alternative = "two.sided", paired = FALSE)


## mean copy by group %>% 
model_random_slopes_data %>% 
  ungroup() %>% 
  filter(n!=0) %>% 
  select(age_f, n,demo_quality_f ) %>% 
  group_by(age_f, demo_quality_f) %>% 
  summarise( mean_copy = mean(n),
             sd = sd (n))


## define priors
prior_cauchy <- brms::prior_string("cauchy(0, 2.5)", class = "b")

## specify model and fit
model_random_slopes <- brms::brm(formula = n ~ 1 + demo_quality_f * age_f + (1 + demo_quality_f | uniqueID),
          prior = prior_cauchy,
          sample_prior = TRUE,
          data = model_random_slopes_data,
          family = poisson(),
          iter = 6000,
          chains = 5) 

## save results
save(file = paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/poission_regression_all_rounds_slopes.RData'), model_random_slopes)

load(file = paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/poission_regression_all_rounds_slopes.RData'))

## bayes factor test main effects
brms::hypothesis(model_random_slopes,"age_fadolescents > 0")[[1]]$Evid.Ratio 
brms::hypothesis(model_random_slopes,"demo_quality_fmedium < 0")[[1]]$Evid.Ratio 
brms::hypothesis(model_random_slopes,"demo_quality_fworst	 < 0") [[1]]$Evid.Ratio 

## bayes factor test interactions
brms::hypothesis(model_random_slopes,"demo_quality_fmedium:age_fadolescents < 0")[[1]]$Evid.Ratio 
brms::hypothesis(model_random_slopes,"demo_quality_fworst:age_fadolescents = 0")[[1]]$Evid.Ratio 

tab_model(model_random_slopes)
plot_model(model_random_slopes)


```



## When do adults find gems? later then adolescents

```{r gem found when bry group, warning=FALSE, message=FALSE}

## select only one observation per participant
data_gem_found <- all_data %>%  
  filter(gem_found == 1) %>% 
  select(round_gem_found, age_f, demo_quality_f, uniqueID) %>% 
  distinct() 

## gem found when by group across all rounds
data_gem_found %>% 
  ungroup() %>% 
  select(age_f, round_gem_found, demo_quality_f, uniqueID ) %>% 
  group_by(uniqueID) %>% 
  mutate( mean_round_gem_found = mean(round_gem_found),
             sd = sd (round_gem_found)) %>% 
  select(mean_round_gem_found, age_f,uniqueID) %>% 
  distinct() %>% 
  ungroup() %>% 
  stats::t.test(mean_round_gem_found ~ age_f, data = ., alternative = "two.sided", paired = FALSE)

## mean round gem found by group and social information use 
data_gem_found %>% 
  ungroup() %>% 
  select(age_f, round_gem_found, demo_quality_f ) %>% 
  group_by(age_f, demo_quality_f) %>% 
  summarise( mean_round_gem_found = mean(round_gem_found),
             sd = sd (round_gem_found))

hist(data_gem_found$round_gem_found)


## load model if fitting has been done, if not fit model
if (file.exists(paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/gem_found_when_model.RData'))){
  
  base::load(paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/gem_found_when_model.RData'))
  
  } else {
  

## model specification
gem_found_when_model <- brms::brm(formula = round_gem_found ~  demo_quality_f * age_f + (1 | uniqueID),
          data = data_gem_found,
          family = poisson(),
          iter = 6000,
          chains = 5) 

## save results
save(file = paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/gem_found_when_model.RData'), gem_found_when_model)

  }

## bayes factor test main effects
brms::hypothesis(gem_found_when_model,"age_fadolescents <  0")[[1]]$Evid.Ratio 
brms::hypothesis(gem_found_when_model,"demo_quality_fmedium < 0")[[1]]$Evid.Ratio 
brms::hypothesis(gem_found_when_model,"demo_quality_fworst	 < 0")[[1]]$Evid.Ratio 

## bayes factor test interactions
brms::hypothesis(gem_found_when_model,"demo_quality_fmedium:age_fadolescents < 0")[[1]]$Evid.Ratio 
brms::hypothesis(gem_found_when_model,"demo_quality_fworst:age_fadolescents <  0")[[1]]$Evid.Ratio 

tab_model(gem_found_when_model)
plot_model(gem_found_when_model)

summary(gem_found_when_model)

```

## extra analyses trial by trial

```{r}

all_data %>% 
  ungroup %>% 
  group_by(unique_rounds) %>% 
  mutate(running_total = cumsum(points)) %>% 
  ggplot() +
  stat_summary(aes(x = trial, y = running_total, color= as.factor(group))) +
  facet_wrap(~demo_quality)
  
all_data %>% 
  ungroup %>% 
  group_by(unique_rounds) %>% 
  mutate(running_total = cumsum(points)) %>% 
  ggplot() +
  stat_summary(aes(x = trial, y = points, color= as.factor(group))) +
  facet_wrap(~demo_quality)

trial_by_trial_scaled_points <- all_data %>%
  ungroup() %>%
  select(uniqueID, age_f, demo_quality_f, points, trial, gempresent, unique_rounds) %>%
  distinct() %>% 
  group_by(factor(gempresent)) %>% 
  mutate(mean_points = mean(points),
         sd = sd(points),
         scaled_points = (points - mean_points)/(sd*0.5))

summary(lmer(points ~ trial + group * demo_quality +(1|uniqueID), data = all_data))

trial_by_trial_scaled_points %>% 
  ungroup() %>% 
  group_by(unique_rounds) %>% 
  mutate(running_total = cumsum(scaled_points)) %>% 
  ggplot() +
  stat_summary(aes(x = trial, y = scaled_points, color= as.factor(age_f))) +
  facet_wrap(~demo_quality_f)


## finish this

## load model if fitting has been done, if not fit model
if (file.exists(paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/points_by_trial.RData'))){
  
  base::load(paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/points_by_trial.RData'))
  
  } else {
  
## model specification
points_by_trial <- brms::brm(scaled_points ~ trial + age_f * demo_quality_f +(1|uniqueID), data = trial_by_trial_scaled_points, chains = 4, iter = 4000)

save(file = paste0(here(),'/G_Analysis_bevioral_data_social/modelfits/points_by_trial.RData'), points_by_trial)

  }


```

